export const BAIRROS_BELEM: string[] = [
  'Batista Campos',
  'Campina',
  'Cidade Velha',
  'Comércio',
  'Condor',
  'Cremação',
  'Guamá',
  'Jurunas',
  'Marco',
  'Marambaia',
  'Nazaré',
  'Pedreira',
  'Reduto',
  'Sacramenta',
  'Souza',
  'São Brás',
  'Telégrafo',
  'Terra Firme',
  'Umarizal',
  'Val-de-Cães',
]
